### PR TITLE
Fix participation valid range

### LINKED ISSUE #166: Error Message : Message Command Error Expected
image

I missed the value for `pp/`, but i think the better error message would be about invalid formatting?

Current behavior :. PP number is out of range..

**Expected Behaviour :** Invalid command ..

### LINKED ISSUE #170: Error Message : Input Participation
image

Think the error message can talk about the max limit to participation points since the error message seems to not solve the user's problem

**Expected Behaviour** : Maximum amount of participation points allowed is...

### PR DESCRIPTION
**Pull request by et-irl**
## Description

This is with regards to `inputPP` and `inputGroupPP`.
Fixes the issue where if pp/ is not included, it would be happy.
Fixes the issue where if pp/ is `2147483647`, weird overflows can happen.

## Context

Closes #166, closes #170.

## Checklist

- [ ] I have self-reviewed my changes.
- [ ] I have added JavaDocs to all relevant methods.
- [x] I have updated the documentation: 
  - User Guide Table of Contents, Description and Summary.
  - Developer Guide, if applicable.
- [x] I have ran `./gradlew test` or `./gradlew check` and all checks pass.
- [x] I have updated my project portfolio with what I have contributed.

### CODE REVIEW

**Review by Vanessamae23 — COMMENTED** [review]
image


Overflow still happens, is this expected?

**Review by Vanessamae23 — COMMENTED** [review]
image

Is it better if we throw invalid command format for this

**Comment by et-irl** [comment]
> image
> 
> Is it better if we throw invalid command format for this

This is fine, as
- Other commands also exhibit a similar behaviour upon an available prefix, but a missing parameter.
- The error message is not wrong, we are looking for a non-negative number.

> image
> 
> Overflow still happens, is this expected?

The difficulty here is that [Integer.parseInt(String s)](http://docs.oracle.com/javase/6/docs/api/java/lang/Integer.html#parseInt%28java.lang.String%29) throws a NumberFormatException for any parse error, including overflow. We have no way to determine if the input is not a Number, or an overflowed number. The best we can do is give a generalised message for this error.

We can compromise and use a more general error message, is this better?

**Review by Choonyan02 — APPROVED** [review]
LGTM!

**Pull request merged**
